### ISSUE TITLE
The software is stuck on the start page

### ISSUE THREAD

**Issue by MillionZBW** [paulpacifico/shutter-encoder#171]
![image](https://github.com/paulpacifico/shutter-encoder/assets/23210456/d2a667f6-0e59-4958-87f8-0f6be9b29193)
Hello developer, I downloaded the portable version from the official website. But the software won't start, as shown in the picture

**Comment by paulpacifico** [comment]
Hello, what is your OS? Did you try the install version?

Paul.

**Comment by JZBo** [comment]
Hello, I am writing to report that I am having the same issue. 
Portable version does not work (tried 17.7, 17.6, 17.5 and 17.4), gets stuck while loading, pretty much at the same spot MillionZBW put in his screenshot.
Installed version works. I would prefer being able to use the portable one, though.

My OS is Windows10 64bit, 21H2

**Comment by paulpacifico** [comment]
Could you try to run this command (replace the _FullPathTo_ with the portable path) press enter and copy paste the log here:

`"C:\Program Files\Shutter Encoder\JRE\bin\java.exe" -jar "FullPathTo/Shutter Encoder.exe"`

**Comment by paulpacifico** [comment]
Could you try to run this command (replace the FullPathTo with the portable path) press enter and copy paste the log here:

`"C:\Program Files\Shutter Encoder\JRE\bin\java.exe" -jar "FullPathTo/Shutter Encoder.exe"`

**Comment by 2-click** [comment]
Same issue. Windows 11, portable version is stuck at startup. Installed it works.

**Comment by x9t9** [comment]
Same here on win10 Pro 22H2 

<strike>It seems that some dependency is missing 
[ BTW - All antivirus and Firewalls off ] 
[ Just a guess ] - I have few computers - and seems only one of them has that issue - and it is the one that has a nearly new Install - which made me think there might be some dependency package missing - that on other computers was already installed maybe with some other software package or update.</strike>

EDIT :

It seems I have resolved this issue - 

### **_**TL,DR;**_**
The portable folder apparently must be in a path without `special characters` that are Non-unicode or actually - Only Latin characters and no Foreign Encoding

E.g. - `a-zA-Z0-9`

### **Longer Version :**

Following @paulpacifico Suggestion - the output was 
```
java.io.FileNotFoundException: X:\%23EXE%23\WRZ-VIDEO\shutter. Encoder.II\Shutter Encoder 19.3 Windows 64bits\Languages\en.properties (The system cannot find the path specified)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "javax.swing.JComboBox.getSelectedItem()" is null
        at application.Shutter.StatusBar(Shutter.java:19309)
        at application.Shutter.<init>(Shutter.java:926)
        at application.Shutter.main(Shutter.java:831)

```
The Path you see as `X:\%23EXE%23` was actually `X:\#EXE#`  and it appears that the `#` is was the culprit.

What made me think of this was the screenshot from @MillionZBW above - where I saw Chinese characters in the background.
In fact I have tested other Characters like Arab Hebrew Chinese Japanese - Even German Umlaut ( ä, ö, Ü ) - and for me at least, on My machines  - it always failed.

### **User Solution :**
When moving the folder to a "Neutral" latin characters path - it just worked.

### **Issue:**
Foreign Users that might have Foreign Language OS or default Locale Encoding  ( See Screenshot ) - and thus some Default folders ( Like `Desktop` or `Downloads` or even the whole User Name folder ) might be in Foreign Encoding which will create this issue.

<img width="1007" height="545" alt="Image" src="https://github.com/user-attachments/assets/3d7a47c6-0b22-4217-bc5e-9bae1ba10024" />

### **Dev Solution:**
Need to make sure that the Launcher supports non-Unicode or foreign characters as well as other Characters than `a-zA-Z0-9`
Maybe Need to open a Specific Issue for that.

### **Testing:**
Here are some random foreign Characters for those without Foreign Keyboard settings who wants to Copy and Paste :
Chinese : `东西`,`错误`
Hebrew : `דגע`,`אבט`
Japanese : `エラー`,`何か`
Arab:  `شئ ما`,`خطأ`
Other Failures : `!`,`#`,~` etc..

All failed on my specific Machines Setups.

**Comment by brupec** [comment]
same issue here, portable
D:\Tools\Shutter Encoder (Encodage) WORKING
D:\Tools\[Video]\Shutter Encoder (Encodage) NOT WORKING

Probably the [ and ] creating the issue
